spring:
  profiles: default
  redis:
    port: 6379
    host: 10.22.7.122
    password: Vnpay@123
    database: 0
    timeout: 120
    sentinel:
      master: redismaster
      nodes: 10.22.7.122:6379,10.22.7.121:6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 5
        max-active: 8
        max-wait: -1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5
        max-wait: -1
  devtools:
    livereload:
      enabled: true
---

spring:
  profiles: vnpay
  redis:
    port: 6379
    host: 10.22.7.122
    password: Vnpay@123